BAPP-4396: Deprecate self service activation. Update doc URLs
BankIDNorge/bankid-app-activation-spi pull request #1
Opened 2023-03-27 11:57 UTC by Joachricar

2023-03-31 07:03 UTC, okaune commented on outgoingra/src/main/java/no/bankid/outgoing/ra/RaRequirements.java
Consider if we should write something other than "Will be deprecated in 2023". Should discuss how we communicate the deprication of self-service

2023-04-17 13:38 UTC, shadone approved these changes

2023-04-17 13:40 UTC, shadone requested changes

2023-04-17 13:40 UTC, shadone commented on docs/swagger.json
> +              "example" : "{\"no\":\"med aktiveringskoder gitt p� email til que***@xyz.no og p� sms til XXX XX X42\",\"en\":\"using activation codes by email to que***@xyz.no and sms to XXX XX X42\"}
hm, there are some unicode problems it seems. It was fine in the original file but garbled in this PR

2023-04-28 09:37 UTC, shadone approved these changes

2023-04-28 09:40 UTC, merged